# fly.toml app configuration file generated for chatbot-backend-bold-lake-8598 on 2024-10-09T01:52:29+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot-backend-bold-lake-8598'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
